import { phrasesFor, JOIN } from './phrases.js';

// One entry per Gruppenwerk company with a Google Business Profile.
//
// placeId: verified against Google Maps — each one was resolved back to the
// business name, website and phone number before being put here. It makes the
// review link open Google's review dialog directly instead of the map listing.
//
// The review suggestions are generated, not picked from a list: see the grammar
// fields (open / quality / extra / close / kw) and src/review-text.js. Wording is
// taken from what each company says about itself on its own site.

// Remarks that fit any of the trades.
const CRAFT_QUALITY = [
  'Saubere Arbeit und alles termingerecht.',
  'Pünktlich, freundlich und die Baustelle war jeden Abend besenrein.',
  'Die Absprachen haben von Anfang bis Ende gestimmt.',
  'Das Angebot war fair und transparent, keine bösen Überraschungen.',
  'Man wurde die ganze Zeit auf dem Laufenden gehalten.',
  'Sehr ordentliche Ausführung und ein freundliches Team.',
  'Termine wurden eingehalten und die Qualität stimmt.',
  'Kurzfristig einen Termin bekommen und alles lief reibungslos.',
  'Vorher in Ruhe beraten worden, danach genau so umgesetzt.',
  'Sauber gearbeitet und am Ende alles ordentlich hinterlassen.',
];

const CLOSERS = [
  'Für {kw} eine klare Empfehlung.',
  'Können wir für {kw} nur weiterempfehlen.',
  'Wer {kw} sucht, ist hier richtig.',
  'Absolut empfehlenswert für {kw}.',
  'Von uns eine klare Empfehlung für {kw}.',
  'Gerne wieder – top Adresse für {kw}.',
  'Wir würden für {kw} jederzeit wieder dort anrufen.',
];

// Stichworte für den Prompt-Modus: kurze Fragmente, aus denen der Kunde seinen
// eigenen Satz baut. Bewusst keine fertigen Sätze — der Text soll von ihm sein.
const GOOD = ['pünktlich', 'sauber gearbeitet', 'freundlich', 'faire Beratung', 'schnell da', 'gute Qualität'];

export const companies = [
  {
    slug: 'hantke',
    name: 'Maler Hantke',
    legal: 'Tomas Hantke Malermeister GmbH',
    trade: 'Malerbetrieb',
    address: 'Bötelkamp 31, 22529 Hamburg',
    site: 'maler-hantke.de',
    logo: 'hantke.svg',
    accent: '#e85230',
    placeId: 'ChIJByqmffSDsUcRSW_ntQJGvpo',
    hints: { did: ['Wohnung gestrichen', 'Fassade gestrichen', 'tapeziert', 'Boden verlegt', 'nach Wasserschaden', 'Türen lackiert', 'in Hamburg'], good: GOOD },
    open: [
      ['Maler Hantke hat unsere Wohnung komplett gestrichen und tapeziert.', 'Malerarbeiten in Hamburg', 'einen Malerbetrieb in Hamburg', 'Tapezierarbeiten in Hamburg'],
      ['Wir haben das Treppenhaus von Maler Hantke neu streichen lassen.', 'Malerarbeiten in Hamburg', 'einen Maler in Hamburg'],
      ['Die Fassade unseres Hauses wurde von Maler Hantke gestrichen.', 'einen Fassadenanstrich in Hamburg', 'einen Malerbetrieb in Hamburg'],
      ['Wände spachteln und glätten, dann streichen – alles von Maler Hantke.', 'Malerarbeiten in Hamburg', 'einen Maler in Hamburg'],
      ['Maler Hantke hat bei uns Türen und Fenster lackiert.', 'Lackierarbeiten in Hamburg', 'einen Malerbetrieb in Hamburg'],
      ['Nach einem Wasserschaden hat Maler Hantke die Bautrocknung und die Renovierung übernommen.', 'Bautrocknung in Hamburg', 'einen Malerbetrieb in Hamburg'],
      ['Wir haben unser Büro von Maler Hantke neu streichen lassen.', 'Malerarbeiten in Hamburg', 'einen Maler in Hamburg'],
      ['Boden verlegen und Wände streichen – Maler Hantke hat beides gemacht.', 'Bodenverlegung in Hamburg', 'einen Malerbetrieb in Hamburg'],
      ['Maler Hantke hat unsere Altbauwohnung vor dem Einzug renoviert.', 'Malerarbeiten in Hamburg', 'einen Malerbetrieb in Hamburg'],
      ['Nach dem Umbau hat Maler Hantke bei uns Malerarbeiten und die Küchenmontage erledigt.', 'Malerarbeiten in Hamburg', 'einen Maler in Hamburg'],
      ['Die Decken und Wände in unserer Wohnung hat Maler Hantke frisch gestrichen.', 'Malerarbeiten in Hamburg', 'einen Maler in Hamburg'],
      ['Maler Hantke hat unser Ladenlokal über Nacht renoviert.', 'Malerarbeiten in Hamburg', 'einen Malerbetrieb in Hamburg'],
      ['Wir haben die Fenster und Zargen von Maler Hantke lackieren lassen.', 'Lackierarbeiten in Hamburg', 'einen Maler in Hamburg'],
      ['Nach dem Auszug hat Maler Hantke die Wohnung wieder hergerichtet.', 'Malerarbeiten in Hamburg', 'einen Malerbetrieb in Hamburg'],
      ['Maler Hantke hat bei uns Raufaser entfernt und die Wände geglättet.', 'Tapezierarbeiten in Hamburg', 'Malerarbeiten in Hamburg'],
    ],
    quality: CRAFT_QUALITY,
    extra: [
      'Die Farbberatung vorab war richtig hilfreich.',
      'Der Meisterbetrieb sitzt in Hamburg-Lokstedt, das ging entsprechend schnell.',
      'Auch die Kleinigkeiten am Ende wurden ohne Diskussion erledigt.',
      'Möbel und Böden waren sorgfältig abgeklebt.',
      'Es wurde ehrlich gesagt, was nötig ist und was nicht.',
    ],
    close: CLOSERS,
  },
  {
    slug: 'brink',
    name: 'Tischlerei Brink',
    legal: 'Karl Brink Tischlereibetrieb GmbH',
    trade: 'Fenster, Türen & Sicherheit',
    address: 'Heselstücken 10, 22453 Hamburg',
    site: 'tischlerei-brink.de',
    logo: 'brink.svg',
    accent: '#2745e0',
    placeId: 'ChIJU6-8J1WPsUcRE5wQ-gjjRNE',
    hints: { did: ['Fenster repariert', 'Dichtungen getauscht', 'Einbruchschutz', 'Notdienst', 'Wartung', 'Tür repariert', 'in Hamburg'], good: GOOD },
    open: [
      ['Die Tischlerei Brink hat unsere alten Holzfenster reparieren statt austauschen können.', 'Fensterreparatur in Hamburg', 'eine Tischlerei in Hamburg'],
      ['Nach einem Einbruchversuch hat Brink unsere Fenster nachgerüstet.', 'Einbruchschutz an Fenstern in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Bei uns hat die Tischlerei Brink die Fensterdichtungen komplett getauscht.', 'Fensterreparatur in Hamburg', 'Fensterwartung in Hamburg'],
      ['Unser Türschloss war defekt – der Notdienst von Brink war am nächsten Tag da.', 'einen Fenster-Notdienst in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Die Tischlerei Brink macht bei uns die jährliche Wartung von Fenstern und Türen.', 'Fensterwartung in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Brink hat morsche Stellen an unseren Fenstern mit Repair Care saniert.', 'Fensterreparatur in Hamburg', 'eine Tischlerei in Hamburg'],
      ['Wir haben die Haustür von der Tischlerei Brink sichern lassen.', 'Einbruchschutz an Fenstern in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Ein Fenster ließ sich nicht mehr schließen, Brink hat es wieder eingestellt.', 'Fensterreparatur in Hamburg', 'einen Fenster-Notdienst in Hamburg'],
      ['Als Hausverwaltung lassen wir Fenster und Türen regelmäßig von Brink prüfen.', 'Fensterwartung in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Die Tischlerei Brink hat bei uns eine Innentür angepasst und neu eingebaut.', 'eine Tischlerei in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Bei uns hat Brink die Beschläge an allen Fenstern nachgestellt.', 'Fensterwartung in Hamburg', 'Fensterreparatur in Hamburg'],
      ['Die Tischlerei Brink hat unsere Balkontür wieder gangbar gemacht.', 'Fensterreparatur in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Wir haben die Fenster im Treppenhaus von Brink überholen lassen.', 'Fensterwartung in Hamburg', 'eine Tischlerei in Hamburg'],
      ['Brink hat bei uns abschließbare Fenstergriffe montiert.', 'Einbruchschutz an Fenstern in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Nach einem Sturmschaden hat Brink das Fenster noch am selben Tag gesichert.', 'einen Fenster-Notdienst in Hamburg', 'Fensterreparatur in Hamburg'],
    ],
    quality: CRAFT_QUALITY,
    extra: [
      'Die Reparatur war deutlich günstiger als neue Fenster.',
      'Ein Meisterbetrieb, den es in Hamburg seit 1925 gibt – das merkt man.',
      'Es wurde ehrlich gesagt, was sich lohnt und was nicht.',
      'Die Dichtungen wurden gleich mit erneuert.',
      'Innerhalb von 24 Stunden war jemand vor Ort.',
    ],
    close: CLOSERS,
  },
  {
    slug: 'seehafer',
    name: 'Seehafer Elemente',
    legal: 'Alfred Seehafer GmbH',
    trade: 'Türen, Fenster & Funktionstechnik',
    address: 'Heselstücken 10, 22453 Hamburg',
    site: 'seehafer-elemente.de',
    logo: 'seehafer.svg',
    accent: '#ff4202',
    placeId: 'ChIJB1w8uPOIsUcR1Hc8hc9ctGo',
    hints: { did: ['Türen gewartet', 'Fenster eingebaut', 'Objekttüren', 'Tür repariert', 'Beratung', 'in Hamburg'], good: GOOD },
    open: [
      ['Seehafer Elemente hat die Objekttüren in unserer Wohnanlage erneuert.', 'Objekttüren in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Wir haben die Fenster im ganzen Haus von Seehafer Elemente einbauen lassen.', 'einen Fensterbauer in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Die Wartung unserer Türen läuft seit Jahren über Seehafer Elemente.', 'die Wartung von Türen in Hamburg', 'Türen und Fenster in Hamburg'],
      ['An unserer Haustür wurden Beschlag und Dichtung von Seehafer Elemente getauscht.', 'Türreparaturen in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Seehafer Elemente hat die Türen in unserer Kita instand gesetzt.', 'Objekttüren in Hamburg', 'Türreparaturen in Hamburg'],
      ['Als Hausverwaltung geben wir Türen und Fenster an Seehafer Elemente.', 'die Wartung von Türen in Hamburg', 'Objekttüren in Hamburg'],
      ['Der Türschließer im Treppenhaus wurde von Seehafer Elemente neu eingestellt.', 'Türreparaturen in Hamburg', 'die Wartung von Türen in Hamburg'],
      ['Seehafer Elemente hat uns bei Brandschutztüren beraten und sie eingebaut.', 'Objekttüren in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Wir haben die Fenster in unserem Hotel von Seehafer Elemente warten lassen.', 'die Wartung von Türen in Hamburg', 'einen Fensterbauer in Hamburg'],
      ['Nach einem Schaden hat Seehafer Elemente unsere Tür kurzfristig repariert.', 'Türreparaturen in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Seehafer Elemente hat die Haustüranlage unserer Wohnanlage ersetzt.', 'Objekttüren in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Wir haben die Wartung der Brandschutztüren an Seehafer Elemente vergeben.', 'die Wartung von Türen in Hamburg', 'Objekttüren in Hamburg'],
      ['Seehafer Elemente hat bei uns defekte Türbänder ausgetauscht.', 'Türreparaturen in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Die Fenster in unserem Verwaltungsgebäude wurden von Seehafer Elemente erneuert.', 'einen Fensterbauer in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Seehafer Elemente hat die Schließanlage neu eingestellt.', 'Türreparaturen in Hamburg', 'die Wartung von Türen in Hamburg'],
    ],
    quality: CRAFT_QUALITY,
    extra: [
      'Wir haben einen festen Ansprechpartner, das macht vieles einfacher.',
      'Der Termin kam innerhalb von zwei Wochen zustande.',
      'Alles wird ordentlich dokumentiert.',
      'Man merkt, dass der Betrieb seit 1948 in Hamburg arbeitet.',
      'Kleinere Mängel wurden direkt mit erledigt.',
    ],
    close: CLOSERS,
  },
  {
    slug: 'werner-bau',
    name: 'Werner Bau',
    legal: 'Werner GmbH Bauunternehmung',
    trade: 'Fassaden- & Gebäudesanierung',
    address: 'Heselstücken 10, 22453 Hamburg',
    site: 'werner-bau.eu',
    logo: 'werner-bau.svg',
    accent: '#d51a29',
    placeId: 'ChIJB1w8uPOIsUcRvkVOcKm1u3A',
    hints: { did: ['Fassade saniert', 'Wohnung saniert', 'Balkon saniert', 'Klinker ausgebessert', 'Treppenhaus', 'in Hamburg'], good: GOOD },
    open: [
      ['Werner Bau hat die Klinkerfassade unseres Altbaus saniert.', 'Fassadensanierung in Hamburg', 'Altbausanierung in Hamburg'],
      ['Unsere Wohnung wurde von Werner Bau komplett saniert.', 'Gebäudesanierung in Hamburg', 'ein Bauunternehmen in Hamburg'],
      ['Die Balkone an unserem Mehrfamilienhaus hat Werner Bau instand gesetzt.', 'Balkonsanierung in Hamburg', 'Gebäudesanierung in Hamburg'],
      ['Werner Bau hat bei uns Putz- und Maurerarbeiten an der Fassade ausgeführt.', 'Fassadensanierung in Hamburg', 'ein Bauunternehmen in Hamburg'],
      ['Wir haben ein öffentliches Gebäude mit Werner Bau saniert.', 'ein Bauunternehmen in Hamburg', 'Gebäudesanierung in Hamburg'],
      ['Werner Bau hat die Sanierung unseres Gewerbeobjekts übernommen.', 'Gebäudesanierung in Hamburg', 'ein Bauunternehmen in Hamburg'],
      ['Nach Feuchteschäden hat Werner Bau die Fassade wieder hergerichtet.', 'Fassadensanierung in Hamburg', 'Gebäudesanierung in Hamburg'],
      ['Die Sanierung unseres Treppenhauses lief komplett über Werner Bau.', 'Gebäudesanierung in Hamburg', 'Altbausanierung in Hamburg'],
      ['Werner Bau hat bei uns alle Gewerke koordiniert – von Putz bis Fliesen.', 'ein Bauunternehmen in Hamburg', 'Gebäudesanierung in Hamburg'],
      ['Wir haben eine denkmalgeschützte Fassade von Werner Bau sanieren lassen.', 'Fassadensanierung in Hamburg', 'Altbausanierung in Hamburg'],
      ['Werner Bau hat die Giebelwand unseres Hauses neu verputzt.', 'Fassadensanierung in Hamburg', 'ein Bauunternehmen in Hamburg'],
      ['Wir haben die Kellersanierung von Werner Bau ausführen lassen.', 'Gebäudesanierung in Hamburg', 'ein Bauunternehmen in Hamburg'],
      ['Werner Bau hat bei uns Risse im Mauerwerk fachgerecht geschlossen.', 'Fassadensanierung in Hamburg', 'Altbausanierung in Hamburg'],
      ['Die Sanierung unserer Gewerbehalle lief über Werner Bau.', 'ein Bauunternehmen in Hamburg', 'Gebäudesanierung in Hamburg'],
      ['Werner Bau hat das Dachgesims unseres Altbaus instand gesetzt.', 'Altbausanierung in Hamburg', 'Fassadensanierung in Hamburg'],
    ],
    quality: CRAFT_QUALITY,
    extra: [
      'Die Ursache wurde vorher analysiert, statt einfach drüberzustreichen.',
      'Ein Ansprechpartner für alles – das hat viel Abstimmung gespart.',
      'Der Betrieb ist VOB-präqualifiziert, das war für uns wichtig.',
      'Bei den historischen Klinkerfassaden merkt man die Erfahrung.',
      'Der Zeitplan wurde trotz Umfang gehalten.',
    ],
    close: CLOSERS,
  },
  {
    slug: 'werner-geruestbau',
    name: 'J. Werner Gerüstbau',
    legal: 'J. Werner Gerüstbau GmbH & Co. KG',
    trade: 'Gerüstbau',
    address: 'Werner-Siemens-Str. 105, 22113 Hamburg',
    site: 'j-werner-geruestbau.de',
    logo: 'werner-geruestbau.svg',
    accent: '#b8860b',
    placeId: 'ChIJhRygz1SMsUcRyjCvXIrU6AI',
    hints: { did: ['Haus eingerüstet', 'Fassadengerüst', 'Wetterschutzdach', 'kurzfristig gestellt', 'in Hamburg'], good: GOOD },
    open: [
      ['J. Werner Gerüstbau hat unser Einfamilienhaus eingerüstet.', 'Gerüstbau in Hamburg', 'einen Gerüstbauer in Hamburg'],
      ['Für die Fassadensanierung hat Werner Gerüstbau kurzfristig ein Gerüst gestellt.', 'Fassadengerüste in Hamburg', 'Gerüstbau in Hamburg'],
      ['Werner Gerüstbau hat ein Wetterschutzdach über unsere Baustelle gebaut.', 'ein Wetterschutzdach in Hamburg', 'einen Gerüstbauer in Hamburg'],
      ['Unser Wohnprojekt wurde von J. Werner Gerüstbau eingerüstet.', 'Fassadengerüste in Hamburg', 'Gerüstbau in Hamburg'],
      ['Werner Gerüstbau hat das Gerüst für unsere Dachsanierung gestellt.', 'Gerüstbau in Hamburg', 'einen Gerüstbauer in Hamburg'],
      ['Für ein öffentliches Gebäude hat Werner Gerüstbau das Gerüst gestellt.', 'Gerüstbau in Hamburg', 'Fassadengerüste in Hamburg'],
      ['Wir haben eine Sonderkonstruktion von Werner Gerüstbau bauen lassen.', 'einen Gerüstbauer in Hamburg', 'Gerüstbau in Hamburg'],
      ['Das Gerüst für unsere Klinkerfassade kam von J. Werner Gerüstbau.', 'Fassadengerüste in Hamburg', 'Gerüstbau in Hamburg'],
      ['Werner Gerüstbau hat auf- und nach Absprache sofort wieder abgebaut.', 'Gerüstbau in Hamburg', 'Gerüste im Hamburger Umland'],
      ['Wir haben für unser Bauvorhaben mit J. Werner Gerüstbau gearbeitet.', 'Gerüstbau in Hamburg', 'Gerüste im Hamburger Umland'],
      ['Werner Gerüstbau hat unser Mehrfamilienhaus komplett eingerüstet.', 'Fassadengerüste in Hamburg', 'Gerüstbau in Hamburg'],
      ['Für die Dachdecker hat Werner Gerüstbau das Gerüst samt Schutznetz gestellt.', 'Gerüstbau in Hamburg', 'einen Gerüstbauer in Hamburg'],
      ['Wir haben das Gerüst für unsere Malerarbeiten bei Werner Gerüstbau bestellt.', 'Gerüstbau in Hamburg', 'Fassadengerüste in Hamburg'],
      ['Werner Gerüstbau hat bei uns ein Gerüst im engen Hinterhof aufgebaut.', 'einen Gerüstbauer in Hamburg', 'Gerüste im Hamburger Umland'],
      ['Das Gerüst für unser Bauvorhaben im Umland kam von Werner Gerüstbau.', 'Gerüste im Hamburger Umland', 'Gerüstbau in Hamburg'],
    ],
    quality: [
      'Aufbau pünktlich, das Gerüst stand sicher, Abbau nach Absprache sofort.',
      'Unkompliziert, zuverlässig und faires Angebot.',
      'Die Absprachen haben von Anfang bis Ende gestimmt.',
      'Termintreue und Sicherheit waren top.',
      'Rückfragen wurden sofort geklärt.',
      'Angebot kam schnell und war transparent.',
      'Sehr angenehme Zusammenarbeit von der Anfrage bis zum Abbau.',
      'Alles nach Vorschrift und ohne Verzögerung.',
    ],
    extra: [
      'Präqualifiziert nach VOB und voll versichert – das war für uns Voraussetzung.',
      'Man merkt, dass der Betrieb seit 1976 in Hamburg Gerüste baut.',
      'Auch kurzfristige Änderungen waren kein Problem.',
      'Das Gerüst war jederzeit sicher begehbar.',
    ],
    close: CLOSERS,
  },
  {
    slug: 'mehlig',
    name: 'Tischlerei Mehlig',
    legal: 'tischlerei mehlig gmbH',
    trade: 'Innenausbau & Objekteinrichtung',
    address: 'Beesenweide 14, 25436 Moorrege',
    site: 'mehlig-gmbh.de',
    logo: 'mehlig.svg',
    accent: '#c72b16',
    placeId: 'ChIJbbSAYEp-sUcRfGM5cA8YWJo',
    hints: { did: ['Einbauschrank nach Maß', 'Innenausbau', 'Küche nach Maß', 'Restaurant eingerichtet', 'Büro eingerichtet', 'in Moorrege'], good: GOOD },
    open: [
      ['Die Tischlerei Mehlig hat unseren kompletten Innenausbau umgesetzt.', 'Innenausbau im Raum Hamburg', 'eine Tischlerei in Moorrege'],
      ['Wir haben Einbauschränke nach Maß von der Tischlerei Mehlig bauen lassen.', 'Möbel nach Maß bei Hamburg', 'eine Tischlerei in Moorrege'],
      ['Unser Restaurant wurde von Mehlig eingerichtet.', 'Objekteinrichtung im Raum Hamburg', 'Innenausbau im Raum Hamburg'],
      ['Die Tischlerei Mehlig hat unsere Büroeinrichtung gebaut und montiert.', 'Objekteinrichtung im Raum Hamburg', 'Möbel nach Maß bei Hamburg'],
      ['Für unser Hotel hat Mehlig den Innenausbau übernommen.', 'Innenausbau im Raum Hamburg', 'Objekteinrichtung im Raum Hamburg'],
      ['Maßmöbel fürs Wohnzimmer – gebaut von der Tischlerei Mehlig.', 'Möbel nach Maß bei Hamburg', 'eine Tischlerei im Kreis Pinneberg'],
      ['Die Tischlerei Mehlig hat unsere Küche nach Maß gefertigt.', 'Möbel nach Maß bei Hamburg', 'eine Tischlerei in Moorrege'],
      ['Wir haben unseren Ladenbau von Mehlig machen lassen.', 'Objekteinrichtung im Raum Hamburg', 'Innenausbau im Raum Hamburg'],
      ['Mehlig hat bei uns Wandverkleidungen und Einbauten gefertigt.', 'Innenausbau im Raum Hamburg', 'eine Tischlerei im Kreis Pinneberg'],
      ['Vom Entwurf bis zur Montage lief alles über die Tischlerei Mehlig.', 'Innenausbau im Raum Hamburg', 'eine Tischlerei in Moorrege'],
      ['Die Tischlerei Mehlig hat unsere Garderobe nach Maß gebaut.', 'Möbel nach Maß bei Hamburg', 'eine Tischlerei in Moorrege'],
      ['Wir haben den Empfangstresen für unser Büro bei Mehlig bauen lassen.', 'Objekteinrichtung im Raum Hamburg', 'Innenausbau im Raum Hamburg'],
      ['Mehlig hat unser Dachgeschoss komplett ausgebaut.', 'Innenausbau im Raum Hamburg', 'eine Tischlerei im Kreis Pinneberg'],
      ['Die Tischlerei Mehlig hat unsere Praxiseinrichtung gefertigt und montiert.', 'Objekteinrichtung im Raum Hamburg', 'Möbel nach Maß bei Hamburg'],
      ['Für unsere Ferienwohnung hat Mehlig die komplette Einrichtung gebaut.', 'Innenausbau im Raum Hamburg', 'Möbel nach Maß bei Hamburg'],
    ],
    quality: [
      'Handwerklich auf einem sehr hohen Niveau verarbeitet.',
      'Termine wurden gehalten und die Qualität ist außergewöhnlich.',
      'Beratung, Materialauswahl und Ausführung waren erstklassig.',
      'Alles millimetergenau eingepasst.',
      'Diskret, sauber und absolut zuverlässig.',
      'Sehr sorgfältig gearbeitet, bis ins Detail.',
      'Die Absprachen haben von Anfang bis Ende gestimmt.',
      'Individuelle Lösungen statt Standard von der Stange.',
    ],
    extra: [
      'Auch Sonderwünsche waren kein Problem.',
      'Die Montage vor Ort lief völlig unkompliziert.',
      'Man kann dem Betrieb auch größere Projekte bedenkenlos anvertrauen.',
      'Die Werkstatt in Moorrege ist einen Besuch wert.',
    ],
    close: CLOSERS,
  },
  {
    slug: 'bsi',
    name: 'Gruppenwerk BSI',
    legal: 'Gruppenwerk BSI Bausanierung und Instandhaltung GmbH',
    trade: 'Sanierung, Planung & Leckortung',
    address: 'Bötelkamp 31, 22529 Hamburg',
    site: 'gruppenwerk-bau.de',
    logo: 'bsi.png',
    accent: '#bb1f11',
    placeId: 'ChIJOf0w2FSPsUcRjEHWjKireJw',
    hints: { did: ['Sanierung geplant', 'Bauleitung', 'Leckortung', 'Bauantrag', 'Dachaufstockung', 'in Hamburg'], good: GOOD },
    open: [
      ['Gruppenwerk BSI hat unsere Dachaufstockung geplant und die Bauleitung übernommen.', 'Bauleitung in Hamburg', 'Sanierungsplanung in Hamburg'],
      ['Die Leckortung von Gruppenwerk BSI hat unseren Wasserschaden punktgenau gefunden.', 'Leckortung in Hamburg', 'Bausanierung in Hamburg'],
      ['Unsere Wohnung wurde von Gruppenwerk BSI komplett saniert.', 'Bausanierung in Hamburg', 'Sanierungsplanung in Hamburg'],
      ['Gruppenwerk BSI hat für uns den Bauantrag gestellt und begleitet.', 'einen Bauantrag in Hamburg', 'Sanierungsplanung in Hamburg'],
      ['Vom Aufmaß bis zur fertigen Sanierung lief alles über Gruppenwerk BSI.', 'Bausanierung in Hamburg', 'Bauleitung in Hamburg'],
      ['Gruppenwerk BSI hat den Umbau unseres Gebäudes geplant und betreut.', 'Sanierungsplanung in Hamburg', 'Bauleitung in Hamburg'],
      ['Wir haben die Bestandsaufnahme unserer Immobilie von Gruppenwerk BSI machen lassen.', 'Sanierungsplanung in Hamburg', 'Bausanierung in Hamburg'],
      ['Der Ausbau unseres Dachgeschosses wurde von Gruppenwerk BSI gesteuert.', 'Bauleitung in Hamburg', 'Bausanierung in Hamburg'],
      ['Gruppenwerk BSI hat die Sanierung unseres Mehrfamilienhauses koordiniert.', 'Bausanierung in Hamburg', 'Bauleitung in Hamburg'],
      ['Bei unklarer Feuchtigkeit hat Gruppenwerk BSI die Ursache gefunden.', 'Leckortung in Hamburg', 'Bausanierung in Hamburg'],
      ['Gruppenwerk BSI hat den Dachgeschossausbau von der Planung bis zur Abnahme betreut.', 'Bauleitung in Hamburg', 'Sanierungsplanung in Hamburg'],
      ['Wir haben die Bauleitung für unsere Modernisierung an Gruppenwerk BSI gegeben.', 'Bauleitung in Hamburg', 'Bausanierung in Hamburg'],
      ['Gruppenwerk BSI hat den Feuchteschaden in unserem Keller geortet.', 'Leckortung in Hamburg', 'Bausanierung in Hamburg'],
      ['Die Genehmigungsplanung für unseren Anbau kam von Gruppenwerk BSI.', 'einen Bauantrag in Hamburg', 'Sanierungsplanung in Hamburg'],
      ['Gruppenwerk BSI hat unser Gewerbeobjekt umgebaut und die Abnahme begleitet.', 'Bausanierung in Hamburg', 'Bauleitung in Hamburg'],
    ],
    quality: [
      'Klare Ansagen, realistische Termine und ein gutes Ergebnis.',
      'Die Kosten sind im Rahmen geblieben.',
      'Man wird gut informiert und muss sich um nichts kümmern.',
      'Sehr strukturierte Planung und verlässliche Bauleitung.',
      'Die Absprachen haben von Anfang bis Ende gestimmt.',
      'Ehrliche Kostenschätzung ohne Schönrechnen.',
      'Alles aus einer Hand, das hat viel Abstimmung gespart.',
      'Schnell vor Ort und sauber gearbeitet.',
    ],
    extra: [
      'Die Leckortung lief ohne die halbe Wohnung aufzureißen.',
      'Der Bauantrag ist reibungslos durchgegangen.',
      'Uns wurde klar gesagt, welche Maßnahme sich rechnet und welche nicht.',
      'Auch die Handwerker vor Ort waren gut organisiert.',
    ],
    close: CLOSERS,
  },
  {
    slug: 'groundpassion',
    name: 'GroundPassion',
    legal: 'Ein Service von Gruppenwerk BSI GmbH',
    trade: 'Immobilien-Investment',
    address: 'Bötelkamp 31, 22529 Hamburg',
    site: 'groundpassion.de',
    logo: 'groundpassion.svg',
    accent: '#2438d6',
    placeId: 'ChIJzzW09luPsUcRlKippaMOOjY',
    hints: { did: ['Kauf begleitet', 'Objekt geprüft', 'Finanzierung', 'Verkauf begleitet', 'Beratung', 'in Hamburg'], good: GOOD },
    open: [
      ['GroundPassion hat uns beim Kauf unserer ersten Anlageimmobilie begleitet.', 'Anlageimmobilien in Hamburg', 'eine Immobilienberatung in Hamburg'],
      ['Wir haben unsere Investmentstrategie mit GroundPassion entwickelt.', 'Immobilien-Investment in Hamburg', 'eine Immobilienberatung in Hamburg'],
      ['GroundPassion hat unser Portfolio durchgerechnet und optimiert.', 'Immobilien-Investment in Hamburg', 'Kapitalanlagen in Hamburg'],
      ['Beim Verkauf unserer Wohnung wurden wir von GroundPassion beraten.', 'eine Immobilienberatung in Hamburg', 'Anlageimmobilien in Hamburg'],
      ['Die Objektsuche und die Prüfung liefen über GroundPassion.', 'Anlageimmobilien in Hamburg', 'eine Immobilienberatung in Hamburg'],
      ['GroundPassion hat uns bei Finanzierung und Vermietung unterstützt.', 'Kapitalanlagen in Hamburg', 'Immobilien-Investment in Hamburg'],
      ['Wir haben den Immobilien-Quick-Check von GroundPassion genutzt.', 'eine Immobilienberatung in Hamburg', 'Anlageimmobilien in Hamburg'],
      ['GroundPassion begleitet unsere Kapitalanlage seit dem Kauf.', 'Kapitalanlagen in Hamburg', 'Immobilien-Investment in Hamburg'],
      ['Die Standortanalyse für unser Objekt kam von GroundPassion.', 'Anlageimmobilien in Hamburg', 'Immobilien-Investment in Hamburg'],
      ['Wir haben uns von GroundPassion zu einem Objekt in Hamburg beraten lassen.', 'eine Immobilienberatung in Hamburg', 'Kapitalanlagen in Hamburg'],
      ['GroundPassion hat uns durch die gesamte Finanzierung begleitet.', 'Kapitalanlagen in Hamburg', 'eine Immobilienberatung in Hamburg'],
      ['Wir haben zwei Objekte von GroundPassion prüfen lassen.', 'Anlageimmobilien in Hamburg', 'eine Immobilienberatung in Hamburg'],
      ['GroundPassion hat unsere Wohnung neu vermietet und die Verwaltung übernommen.', 'Kapitalanlagen in Hamburg', 'Immobilien-Investment in Hamburg'],
      ['Die Kalkulation für unser erstes Investment kam von GroundPassion.', 'Immobilien-Investment in Hamburg', 'Anlageimmobilien in Hamburg'],
      ['GroundPassion hat uns beim Ausstieg aus einem Objekt beraten.', 'eine Immobilienberatung in Hamburg', 'Immobilien-Investment in Hamburg'],
    ],
    quality: [
      'Fundierte Analysen, realistische Zahlen und kein Verkaufsdruck.',
      'Man bekommt Fakten statt Versprechen.',
      'Auch bei Objekten, die nichts taugen, wurde ehrlich abgeraten.',
      'Es wird langfristig gedacht statt schnell verkauft.',
      'Die Absprachen haben von Anfang bis Ende gestimmt.',
      'Sehr transparent, jede Zahl war nachvollziehbar.',
      'Erreichbar, verlässlich und gut vorbereitet.',
    ],
    extra: [
      'Die Rückmeldung zum Objekt kam sehr schnell.',
      'Auch nach dem Kauf war jemand ansprechbar.',
      'Die Finanzierung wurde gleich mit durchgerechnet.',
    ],
    close: CLOSERS,
  },
  {
    slug: 'networking',
    name: 'Gruppenwerk Networking',
    legal: 'Gruppenwerk Networking GmbH',
    trade: 'Coworking für Bau & Immobilien',
    address: 'Bötelkamp 31, 22529 Hamburg',
    site: 'gruppenwerk-networking.de',
    logo: 'networking.png',
    accent: '#7ba800',
    // Kein eigenes Google-Unternehmensprofil gefunden – der Link führt auf die
    // Google-Maps-Suche. Sobald ein Profil existiert, hier die Place ID eintragen.
    placeId: null,
    hints: { did: ['Schreibtisch gemietet', 'Büro gemietet', 'Meetingräume', 'Coworking', 'in Hamburg'], good: GOOD },
    open: [
      ['Wir sind als kleines Team bei Gruppenwerk Networking eingezogen.', 'Coworking in Hamburg', 'ein Büro in Hamburg'],
      ['Wir arbeiten seit einiger Zeit im Coworking von Gruppenwerk Networking.', 'Coworking in Hamburg', 'Coworking in der Bau- und Immobilienbranche'],
      ['Gruppenwerk Networking ist unser Büro in Hamburg geworden.', 'ein Büro in Hamburg', 'einen Büroplatz in Hamburg'],
      ['Wir haben hier einen Schreibtisch im Coworking gemietet.', 'einen Büroplatz in Hamburg', 'Coworking in Hamburg'],
      ['Als Freiberufler sitze ich bei Gruppenwerk Networking.', 'einen Büroplatz in Hamburg', 'Coworking in Hamburg'],
      ['Unser Start-up hat bei Gruppenwerk Networking Büroräume bezogen.', 'ein Büro in Hamburg', 'Coworking in der Bau- und Immobilienbranche'],
      ['Wir nutzen die Meetingräume von Gruppenwerk Networking regelmäßig.', 'Coworking in Hamburg', 'ein Büro in Hamburg'],
      ['Wir haben bei Gruppenwerk Networking zwei feste Arbeitsplätze gemietet.', 'einen Büroplatz in Hamburg', 'Coworking in Hamburg'],
      ['Unser Architekturbüro sitzt seit einem Jahr bei Gruppenwerk Networking.', 'ein Büro in Hamburg', 'Coworking in der Bau- und Immobilienbranche'],
      ['Gruppenwerk Networking ist unser Standort für Kundentermine geworden.', 'ein Büro in Hamburg', 'Coworking in Hamburg'],
      ['Wir nutzen hier Büro und Meetingräume für unser kleines Team.', 'Coworking in Hamburg', 'einen Büroplatz in Hamburg'],
      ['Als Projektentwickler habe ich hier meinen Arbeitsplatz.', 'einen Büroplatz in Hamburg', 'Coworking in der Bau- und Immobilienbranche'],
    ],
    quality: [
      'Modernes Büro, schnelles Internet und gute Meetingräume.',
      'Freundliche Betreuung und eine gute Ausstattung.',
      'Monatlich kündbar, und man kann jederzeit Plätze dazunehmen.',
      'Schöne Räume und faire Konditionen.',
      'Angenehme Lounge und eine gut ausgestattete Küche.',
      'Deutlich besser als ein anonymes Großraumbüro.',
    ],
    extra: [
      'Der Branchenfokus bringt wirklich etwas – hier sitzen Leute aus Bau, Immobilien und Architektur.',
      'Aus den Kontakten sind bei uns schon mehrere Projekte entstanden.',
      'Man kommt hier leicht mit anderen ins Gespräch.',
    ],
    close: CLOSERS,
  },
];

// Jeder Betrieb bekommt seinen eigenen, überschneidungsfreien Anteil am Wortmaterial.
companies.forEach((c, i) => Object.assign(c, phrasesFor(i, companies.length), { join: JOIN }));

export const bySlug = Object.fromEntries(companies.map((c) => [c.slug, c]));

/** Where the customer is sent to leave the review. */
export function reviewUrl(c) {
  return c.placeId
    ? `https://search.google.com/local/writereview?placeid=${encodeURIComponent(c.placeId)}`
    : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${c.name} ${c.address}`)}`;
}
