import { phrasesFor, JOIN } from './phrases.js';

// One entry per Gruppenwerk company with a Google Business Profile.
//
// placeId: verified against Google Maps — each one was resolved back to the
// business name, website and phone number before being put here. It makes the
// review link open Google's review dialog directly instead of the map listing.
//
// The review suggestions are generated, not picked from a list: `open` supplies
// the opening sentence plus the search terms that fit that particular job, and
// `extra` an occasional detail. Everything else comes from src/phrases.js, which
// hands every company its own exclusive slice. Wording follows what each company
// says about itself on its own site, but in the register people actually write
// reviews in — spoken, short, often without the subject pronoun.

// Stichworte für den Prompt-Modus: kurze Fragmente, aus denen der Kunde seinen
// eigenen Satz baut. Bewusst keine fertigen Sätze — der Text soll von ihm sein.
const GOOD = ['pünktlich', 'sauber gearbeitet', 'freundlich', 'faire Beratung', 'schnell da', 'gute Qualität'];

export const companies = [
  {
    slug: 'hantke',
    name: 'Maler Hantke',
    legal: 'Tomas Hantke Malermeister GmbH',
    trade: 'Malerbetrieb',
    address: 'Bötelkamp 31, 22529 Hamburg',
    site: 'maler-hantke.de',
    logo: 'hantke.svg',
    accent: '#e85230',
    placeId: 'ChIJByqmffSDsUcRSW_ntQJGvpo',
    hints: { did: ['Wohnung gestrichen', 'Fassade gestrichen', 'tapeziert', 'Boden verlegt', 'nach Wasserschaden', 'Türen lackiert', 'in Hamburg'], good: GOOD },
    open: [
      ['Haben unsere Wohnung von Maler Hantke streichen und tapezieren lassen.', 'Malerarbeiten in Hamburg', 'einen Malerbetrieb in Hamburg', 'Tapezierarbeiten in Hamburg'],
      ['Treppenhaus neu streichen lassen, gemacht hat es Maler Hantke.', 'Malerarbeiten in Hamburg', 'einen Maler in Hamburg'],
      ['Maler Hantke war bei uns und hat die Fassade gestrichen.', 'einen Fassadenanstrich in Hamburg', 'einen Malerbetrieb in Hamburg'],
      ['Wände spachteln, glätten, streichen: alles von Maler Hantke.', 'Malerarbeiten in Hamburg', 'einen Maler in Hamburg'],
      ['Maler Hantke hat bei uns Türen und Fenster lackiert.', 'Lackierarbeiten in Hamburg', 'einen Malerbetrieb in Hamburg'],
      ['Nach einem Wasserschaden hat Hantke die Bautrocknung und die Renovierung gemacht.', 'Bautrocknung in Hamburg', 'einen Malerbetrieb in Hamburg'],
      ['Büro neu streichen lassen, kam alles von Maler Hantke.', 'Malerarbeiten in Hamburg', 'einen Maler in Hamburg'],
      ['Boden verlegen und Wände streichen, beides von Maler Hantke.', 'Bodenverlegung in Hamburg', 'einen Malerbetrieb in Hamburg'],
      ['Unsere Altbauwohnung wurde vor dem Einzug von Maler Hantke renoviert.', 'Malerarbeiten in Hamburg', 'einen Malerbetrieb in Hamburg'],
      ['Nach dem Umbau hat Hantke bei uns die Malerarbeiten und die Küchenmontage gemacht.', 'Malerarbeiten in Hamburg', 'einen Maler in Hamburg'],
      ['Decken und Wände frisch gestrichen, gemacht von Maler Hantke.', 'Malerarbeiten in Hamburg', 'einen Maler in Hamburg'],
      ['Maler Hantke hat unser Ladenlokal über Nacht renoviert, wir hatten keinen Tag zu.', 'Malerarbeiten in Hamburg', 'einen Malerbetrieb in Hamburg'],
      ['Fenster und Zargen haben wir von Maler Hantke lackieren lassen.', 'Lackierarbeiten in Hamburg', 'einen Maler in Hamburg'],
      ['Nach dem Auszug hat Hantke die Wohnung wieder hergerichtet.', 'Malerarbeiten in Hamburg', 'einen Malerbetrieb in Hamburg'],
      ['Raufaser runter, Wände geglättet, gemacht von Maler Hantke.', 'Tapezierarbeiten in Hamburg', 'Malerarbeiten in Hamburg'],
    ],
    extra: [
      'Die Farbberatung vorher hat wirklich geholfen.',
      'Der Betrieb sitzt in Lokstedt, entsprechend schnell war jemand da.',
      'Die Kleinigkeiten am Ende wurden ohne Diskussion erledigt.',
      'Möbel und Böden waren ordentlich abgeklebt.',
      'Es wurde ehrlich gesagt, was gemacht werden muss und was nicht.',
    ],
  },
  {
    slug: 'brink',
    name: 'Tischlerei Brink',
    legal: 'Karl Brink Tischlereibetrieb GmbH',
    trade: 'Fenster, Türen & Sicherheit',
    address: 'Heselstücken 10, 22453 Hamburg',
    site: 'tischlerei-brink.de',
    logo: 'brink.svg',
    accent: '#2745e0',
    placeId: 'ChIJU6-8J1WPsUcRE5wQ-gjjRNE',
    hints: { did: ['Fenster repariert', 'Dichtungen getauscht', 'Einbruchschutz', 'Notdienst', 'Wartung', 'Tür repariert', 'in Hamburg'], good: GOOD },
    open: [
      ['Die Tischlerei Brink konnte unsere alten Holzfenster reparieren statt austauschen.', 'Fensterreparatur in Hamburg', 'eine Tischlerei in Hamburg'],
      ['Nach einem Einbruchversuch hat Brink unsere Fenster nachgerüstet.', 'Einbruchschutz an Fenstern in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Brink hat bei uns alle Fensterdichtungen getauscht.', 'Fensterreparatur in Hamburg', 'Fensterwartung in Hamburg'],
      ['Türschloss war kaputt, der Notdienst von Brink war am nächsten Tag da.', 'einen Fenster-Notdienst in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Die jährliche Wartung unserer Fenster und Türen macht die Tischlerei Brink.', 'Fensterwartung in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Morsche Stellen an den Fenstern hat Brink mit Repair Care saniert.', 'Fensterreparatur in Hamburg', 'eine Tischlerei in Hamburg'],
      ['Haustür sichern lassen, gemacht hat es die Tischlerei Brink.', 'Einbruchschutz an Fenstern in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Ein Fenster ging nicht mehr zu, Brink hat es wieder eingestellt.', 'Fensterreparatur in Hamburg', 'einen Fenster-Notdienst in Hamburg'],
      ['Wir sind Hausverwaltung und lassen Fenster und Türen regelmäßig von Brink prüfen.', 'Fensterwartung in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Brink hat bei uns eine Innentür angepasst und neu eingebaut.', 'eine Tischlerei in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Beschläge an allen Fenstern nachgestellt, gemacht von Brink.', 'Fensterwartung in Hamburg', 'Fensterreparatur in Hamburg'],
      ['Unsere Balkontür ging schwer, die Tischlerei Brink hat sie wieder gangbar gemacht.', 'Fensterreparatur in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Die Fenster im Treppenhaus haben wir von Brink überholen lassen.', 'Fensterwartung in Hamburg', 'eine Tischlerei in Hamburg'],
      ['Brink hat uns abschließbare Fenstergriffe montiert.', 'Einbruchschutz an Fenstern in Hamburg', 'Fenster und Türen in Hamburg'],
      ['Nach dem Sturm hat Brink das Fenster noch am selben Tag gesichert.', 'einen Fenster-Notdienst in Hamburg', 'Fensterreparatur in Hamburg'],
    ],
    extra: [
      'Die Reparatur war deutlich günstiger als neue Fenster.',
      'Den Betrieb gibt es in Hamburg seit 1925, das merkt man.',
      'Uns wurde ehrlich gesagt, was sich lohnt und was nicht.',
      'Die Dichtungen wurden gleich mitgemacht.',
      'Innerhalb von 24 Stunden war jemand da.',
    ],
  },
  {
    slug: 'seehafer',
    name: 'Seehafer Elemente',
    legal: 'Alfred Seehafer GmbH',
    trade: 'Türen, Fenster & Funktionstechnik',
    address: 'Heselstücken 10, 22453 Hamburg',
    site: 'seehafer-elemente.de',
    logo: 'seehafer.svg',
    accent: '#ff4202',
    placeId: 'ChIJB1w8uPOIsUcR1Hc8hc9ctGo',
    hints: { did: ['Türen gewartet', 'Fenster eingebaut', 'Objekttüren', 'Tür repariert', 'Beratung', 'in Hamburg'], good: GOOD },
    open: [
      ['Seehafer Elemente hat die Objekttüren in unserer Wohnanlage erneuert.', 'Objekttüren in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Die Fenster im ganzen Haus haben wir von Seehafer Elemente einbauen lassen.', 'einen Fensterbauer in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Unsere Türwartung läuft seit Jahren über Seehafer Elemente.', 'die Wartung von Türen in Hamburg', 'Türen und Fenster in Hamburg'],
      ['An der Haustür wurden Beschlag und Dichtung getauscht, gemacht von Seehafer Elemente.', 'Türreparaturen in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Seehafer Elemente hat die Türen in unserer Kita wieder instand gesetzt.', 'Objekttüren in Hamburg', 'Türreparaturen in Hamburg'],
      ['Wir sind Hausverwaltung und geben Türen und Fenster an Seehafer Elemente.', 'die Wartung von Türen in Hamburg', 'Objekttüren in Hamburg'],
      ['Der Türschließer im Treppenhaus war zu stramm, Seehafer Elemente hat ihn neu eingestellt.', 'Türreparaturen in Hamburg', 'die Wartung von Türen in Hamburg'],
      ['Seehafer Elemente hat uns zu Brandschutztüren beraten und sie dann eingebaut.', 'Objekttüren in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Die Fenster in unserem Hotel lassen wir von Seehafer Elemente warten.', 'die Wartung von Türen in Hamburg', 'einen Fensterbauer in Hamburg'],
      ['Nach einem Schaden hat Seehafer Elemente unsere Tür kurzfristig repariert.', 'Türreparaturen in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Seehafer Elemente hat die ganze Haustüranlage ersetzt.', 'Objekttüren in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Die Wartung der Brandschutztüren haben wir an Seehafer Elemente gegeben.', 'die Wartung von Türen in Hamburg', 'Objekttüren in Hamburg'],
      ['Defekte Türbänder ausgetauscht, gemacht von Seehafer Elemente.', 'Türreparaturen in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Die Fenster in unserem Verwaltungsgebäude hat Seehafer Elemente erneuert.', 'einen Fensterbauer in Hamburg', 'Türen und Fenster in Hamburg'],
      ['Schließanlage neu eingestellt, gemacht von Seehafer Elemente.', 'Türreparaturen in Hamburg', 'die Wartung von Türen in Hamburg'],
    ],
    extra: [
      'Wir haben einen festen Ansprechpartner, das macht vieles leichter.',
      'Der Termin kam innerhalb von zwei Wochen.',
      'Alles wird ordentlich dokumentiert.',
      'Den Betrieb gibt es in Hamburg seit 1948, das sieht man an der Arbeit.',
      'Kleinere Mängel wurden direkt mitgemacht.',
    ],
  },
  {
    slug: 'werner-bau',
    name: 'Werner Bau',
    legal: 'Werner GmbH Bauunternehmung',
    trade: 'Fassaden- & Gebäudesanierung',
    address: 'Heselstücken 10, 22453 Hamburg',
    site: 'werner-bau.eu',
    logo: 'werner-bau.svg',
    accent: '#d51a29',
    placeId: 'ChIJB1w8uPOIsUcRvkVOcKm1u3A',
    hints: { did: ['Fassade saniert', 'Wohnung saniert', 'Balkon saniert', 'Klinker ausgebessert', 'Treppenhaus', 'in Hamburg'], good: GOOD },
    open: [
      ['Werner Bau hat die Klinkerfassade an unserem Altbau saniert.', 'Fassadensanierung in Hamburg', 'Altbausanierung in Hamburg'],
      ['Unsere Wohnung wurde von Werner Bau komplett saniert.', 'Gebäudesanierung in Hamburg', 'ein Bauunternehmen in Hamburg'],
      ['Die Balkone an unserem Mehrfamilienhaus hat Werner Bau gemacht.', 'Balkonsanierung in Hamburg', 'Gebäudesanierung in Hamburg'],
      ['Putz- und Maurerarbeiten an der Fassade, gemacht von Werner Bau.', 'Fassadensanierung in Hamburg', 'ein Bauunternehmen in Hamburg'],
      ['Wir haben ein öffentliches Gebäude zusammen mit Werner Bau saniert.', 'ein Bauunternehmen in Hamburg', 'Gebäudesanierung in Hamburg'],
      ['Die Sanierung unseres Gewerbeobjekts hat Werner Bau übernommen.', 'Gebäudesanierung in Hamburg', 'ein Bauunternehmen in Hamburg'],
      ['Nach Feuchteschäden hat Werner Bau die Fassade wieder hergerichtet.', 'Fassadensanierung in Hamburg', 'Gebäudesanierung in Hamburg'],
      ['Unser Treppenhaus wurde komplett von Werner Bau saniert.', 'Gebäudesanierung in Hamburg', 'Altbausanierung in Hamburg'],
      ['Werner Bau hat bei uns alle Gewerke koordiniert, von Putz bis Fliesen.', 'ein Bauunternehmen in Hamburg', 'Gebäudesanierung in Hamburg'],
      ['Denkmalgeschützte Fassade sanieren lassen, gemacht hat es Werner Bau.', 'Fassadensanierung in Hamburg', 'Altbausanierung in Hamburg'],
      ['Die Giebelwand hat Werner Bau neu verputzt.', 'Fassadensanierung in Hamburg', 'ein Bauunternehmen in Hamburg'],
      ['Unsere Kellersanierung haben wir Werner Bau gegeben.', 'Gebäudesanierung in Hamburg', 'ein Bauunternehmen in Hamburg'],
      ['Risse im Mauerwerk hat Werner Bau ordentlich geschlossen.', 'Fassadensanierung in Hamburg', 'Altbausanierung in Hamburg'],
      ['Die Sanierung unserer Gewerbehalle lief über Werner Bau.', 'ein Bauunternehmen in Hamburg', 'Gebäudesanierung in Hamburg'],
      ['Werner Bau hat das Dachgesims an unserem Altbau instand gesetzt.', 'Altbausanierung in Hamburg', 'Fassadensanierung in Hamburg'],
    ],
    extra: [
      'Die Ursache wurde vorher gesucht, statt einfach drüberzustreichen.',
      'Ein Ansprechpartner für alles, das hat uns viel Abstimmung gespart.',
      'Der Betrieb ist VOB-präqualifiziert, das war für uns wichtig.',
      'Bei alten Klinkerfassaden merkt man die Erfahrung.',
      'Trotz des Umfangs hat der Zeitplan gehalten.',
    ],
  },
  {
    slug: 'werner-geruestbau',
    name: 'J. Werner Gerüstbau',
    legal: 'J. Werner Gerüstbau GmbH & Co. KG',
    trade: 'Gerüstbau',
    address: 'Werner-Siemens-Str. 105, 22113 Hamburg',
    site: 'j-werner-geruestbau.de',
    logo: 'werner-geruestbau.svg',
    accent: '#b8860b',
    placeId: 'ChIJhRygz1SMsUcRyjCvXIrU6AI',
    hints: { did: ['Haus eingerüstet', 'Fassadengerüst', 'Wetterschutzdach', 'kurzfristig gestellt', 'in Hamburg'], good: GOOD },
    open: [
      ['J. Werner Gerüstbau hat unser Einfamilienhaus eingerüstet.', 'Gerüstbau in Hamburg', 'einen Gerüstbauer in Hamburg'],
      ['Für die Fassadensanierung hat Werner Gerüstbau kurzfristig ein Gerüst gestellt.', 'Fassadengerüste in Hamburg', 'Gerüstbau in Hamburg'],
      ['Werner Gerüstbau hat ein Wetterschutzdach über unsere Baustelle gebaut.', 'ein Wetterschutzdach in Hamburg', 'einen Gerüstbauer in Hamburg'],
      ['Unser Wohnprojekt wurde von J. Werner Gerüstbau eingerüstet.', 'Fassadengerüste in Hamburg', 'Gerüstbau in Hamburg'],
      ['Das Gerüst für unsere Dachsanierung kam von Werner Gerüstbau.', 'Gerüstbau in Hamburg', 'einen Gerüstbauer in Hamburg'],
      ['Für ein öffentliches Gebäude hat Werner Gerüstbau das Gerüst gestellt.', 'Gerüstbau in Hamburg', 'Fassadengerüste in Hamburg'],
      ['Sonderkonstruktion bauen lassen, gemacht hat es Werner Gerüstbau.', 'einen Gerüstbauer in Hamburg', 'Gerüstbau in Hamburg'],
      ['Das Gerüst für unsere Klinkerfassade kam von J. Werner Gerüstbau.', 'Fassadengerüste in Hamburg', 'Gerüstbau in Hamburg'],
      ['Werner Gerüstbau hat aufgebaut und nach Absprache sofort wieder abgebaut.', 'Gerüstbau in Hamburg', 'Gerüste im Hamburger Umland'],
      ['Für unser Bauvorhaben haben wir mit J. Werner Gerüstbau gearbeitet.', 'Gerüstbau in Hamburg', 'Gerüste im Hamburger Umland'],
      ['Unser Mehrfamilienhaus hat Werner Gerüstbau komplett eingerüstet.', 'Fassadengerüste in Hamburg', 'Gerüstbau in Hamburg'],
      ['Für die Dachdecker hat Werner Gerüstbau Gerüst und Schutznetz gestellt.', 'Gerüstbau in Hamburg', 'einen Gerüstbauer in Hamburg'],
      ['Das Gerüst für unsere Malerarbeiten haben wir bei Werner Gerüstbau bestellt.', 'Gerüstbau in Hamburg', 'Fassadengerüste in Hamburg'],
      ['Enger Hinterhof, trotzdem hat Werner Gerüstbau das Gerüst sauber hinbekommen.', 'einen Gerüstbauer in Hamburg', 'Gerüste im Hamburger Umland'],
      ['Das Gerüst für unser Bauvorhaben im Umland kam von Werner Gerüstbau.', 'Gerüste im Hamburger Umland', 'Gerüstbau in Hamburg'],
    ],
    extra: [
      'Präqualifiziert nach VOB und voll versichert, das war für uns Voraussetzung.',
      'Den Betrieb gibt es in Hamburg seit 1976, das sieht man am Aufbau.',
      'Auch kurzfristige Änderungen waren kein Problem.',
      'Das Gerüst war jederzeit sicher begehbar.',
    ],
  },
  {
    slug: 'mehlig',
    name: 'Tischlerei Mehlig',
    legal: 'tischlerei mehlig gmbH',
    trade: 'Innenausbau & Objekteinrichtung',
    address: 'Beesenweide 14, 25436 Moorrege',
    site: 'mehlig-gmbh.de',
    logo: 'mehlig.svg',
    accent: '#c72b16',
    placeId: 'ChIJbbSAYEp-sUcRfGM5cA8YWJo',
    hints: { did: ['Einbauschrank nach Maß', 'Innenausbau', 'Küche nach Maß', 'Restaurant eingerichtet', 'Büro eingerichtet', 'in Moorrege'], good: GOOD },
    open: [
      ['Unseren kompletten Innenausbau hat die Tischlerei Mehlig gemacht.', 'Innenausbau im Raum Hamburg', 'eine Tischlerei in Moorrege'],
      ['Einbauschränke nach Maß bauen lassen, gemacht hat es die Tischlerei Mehlig.', 'Möbel nach Maß bei Hamburg', 'eine Tischlerei in Moorrege'],
      ['Unser Restaurant wurde von Mehlig eingerichtet.', 'Objekteinrichtung im Raum Hamburg', 'Innenausbau im Raum Hamburg'],
      ['Die Büroeinrichtung hat die Tischlerei Mehlig gebaut und montiert.', 'Objekteinrichtung im Raum Hamburg', 'Möbel nach Maß bei Hamburg'],
      ['Für unser Hotel hat Mehlig den Innenausbau übernommen.', 'Innenausbau im Raum Hamburg', 'Objekteinrichtung im Raum Hamburg'],
      ['Maßmöbel fürs Wohnzimmer, gebaut von der Tischlerei Mehlig.', 'Möbel nach Maß bei Hamburg', 'eine Tischlerei im Kreis Pinneberg'],
      ['Unsere Küche hat die Tischlerei Mehlig nach Maß gefertigt.', 'Möbel nach Maß bei Hamburg', 'eine Tischlerei in Moorrege'],
      ['Den Ladenbau haben wir von Mehlig machen lassen.', 'Objekteinrichtung im Raum Hamburg', 'Innenausbau im Raum Hamburg'],
      ['Mehlig hat bei uns Wandverkleidungen und Einbauten gefertigt.', 'Innenausbau im Raum Hamburg', 'eine Tischlerei im Kreis Pinneberg'],
      ['Vom Entwurf bis zur Montage lief alles über die Tischlerei Mehlig.', 'Innenausbau im Raum Hamburg', 'eine Tischlerei in Moorrege'],
      ['Garderobe nach Maß, gebaut von der Tischlerei Mehlig.', 'Möbel nach Maß bei Hamburg', 'eine Tischlerei in Moorrege'],
      ['Den Empfangstresen für unser Büro haben wir bei Mehlig bauen lassen.', 'Objekteinrichtung im Raum Hamburg', 'Innenausbau im Raum Hamburg'],
      ['Mehlig hat unser Dachgeschoss komplett ausgebaut.', 'Innenausbau im Raum Hamburg', 'eine Tischlerei im Kreis Pinneberg'],
      ['Unsere Praxiseinrichtung hat die Tischlerei Mehlig gefertigt und montiert.', 'Objekteinrichtung im Raum Hamburg', 'Möbel nach Maß bei Hamburg'],
      ['Für unsere Ferienwohnung hat Mehlig die komplette Einrichtung gebaut.', 'Innenausbau im Raum Hamburg', 'Möbel nach Maß bei Hamburg'],
    ],
    extra: [
      'Auch Sonderwünsche waren kein Problem.',
      'Die Montage vor Ort lief völlig unkompliziert.',
      'Auch größere Projekte kann man da bedenkenlos hingeben.',
      'Die Werkstatt in Moorrege ist einen Besuch wert.',
    ],
  },
  {
    slug: 'bsi',
    name: 'Gruppenwerk BSI',
    legal: 'Gruppenwerk BSI Bausanierung und Instandhaltung GmbH',
    trade: 'Sanierung, Planung & Leckortung',
    address: 'Bötelkamp 31, 22529 Hamburg',
    site: 'gruppenwerk-bau.de',
    logo: 'bsi.png',
    accent: '#bb1f11',
    placeId: 'ChIJOf0w2FSPsUcRjEHWjKireJw',
    hints: { did: ['Sanierung geplant', 'Bauleitung', 'Leckortung', 'Bauantrag', 'Dachaufstockung', 'in Hamburg'], good: GOOD },
    open: [
      ['Gruppenwerk BSI hat unsere Dachaufstockung geplant und die Bauleitung gemacht.', 'Bauleitung in Hamburg', 'Sanierungsplanung in Hamburg'],
      ['Die Leckortung von Gruppenwerk BSI hat unseren Wasserschaden punktgenau gefunden.', 'Leckortung in Hamburg', 'Bausanierung in Hamburg'],
      ['Unsere Wohnung wurde von Gruppenwerk BSI komplett saniert.', 'Bausanierung in Hamburg', 'Sanierungsplanung in Hamburg'],
      ['Den Bauantrag hat Gruppenwerk BSI für uns gestellt und begleitet.', 'einen Bauantrag in Hamburg', 'Sanierungsplanung in Hamburg'],
      ['Vom Aufmaß bis zur fertigen Sanierung lief alles über Gruppenwerk BSI.', 'Bausanierung in Hamburg', 'Bauleitung in Hamburg'],
      ['Den Umbau unseres Gebäudes hat Gruppenwerk BSI geplant und betreut.', 'Sanierungsplanung in Hamburg', 'Bauleitung in Hamburg'],
      ['Die Bestandsaufnahme unserer Immobilie haben wir von Gruppenwerk BSI machen lassen.', 'Sanierungsplanung in Hamburg', 'Bausanierung in Hamburg'],
      ['Unseren Dachgeschossausbau hat Gruppenwerk BSI gesteuert.', 'Bauleitung in Hamburg', 'Bausanierung in Hamburg'],
      ['Gruppenwerk BSI hat die Sanierung unseres Mehrfamilienhauses koordiniert.', 'Bausanierung in Hamburg', 'Bauleitung in Hamburg'],
      ['Bei uns war irgendwo Feuchtigkeit, Gruppenwerk BSI hat die Ursache gefunden.', 'Leckortung in Hamburg', 'Bausanierung in Hamburg'],
      ['Gruppenwerk BSI hat unseren Dachausbau von der Planung bis zur Abnahme betreut.', 'Bauleitung in Hamburg', 'Sanierungsplanung in Hamburg'],
      ['Die Bauleitung für unsere Modernisierung haben wir Gruppenwerk BSI gegeben.', 'Bauleitung in Hamburg', 'Bausanierung in Hamburg'],
      ['Den Feuchteschaden im Keller hat Gruppenwerk BSI geortet.', 'Leckortung in Hamburg', 'Bausanierung in Hamburg'],
      ['Die Genehmigungsplanung für unseren Anbau kam von Gruppenwerk BSI.', 'einen Bauantrag in Hamburg', 'Sanierungsplanung in Hamburg'],
      ['Gruppenwerk BSI hat unser Gewerbeobjekt umgebaut und die Abnahme begleitet.', 'Bausanierung in Hamburg', 'Bauleitung in Hamburg'],
    ],
    extra: [
      'Die Leckortung lief, ohne die halbe Wohnung aufzureißen.',
      'Der Bauantrag ist glatt durchgegangen.',
      'Uns wurde klar gesagt, welche Maßnahme sich rechnet und welche nicht.',
      'Auch die Handwerker vor Ort waren gut organisiert.',
    ],
  },
  {
    slug: 'groundpassion',
    name: 'GroundPassion',
    legal: 'Ein Service von Gruppenwerk BSI GmbH',
    trade: 'Immobilien-Investment',
    address: 'Bötelkamp 31, 22529 Hamburg',
    site: 'groundpassion.de',
    logo: 'groundpassion.svg',
    accent: '#2438d6',
    placeId: 'ChIJzzW09luPsUcRlKippaMOOjY',
    hints: { did: ['Kauf begleitet', 'Objekt geprüft', 'Finanzierung', 'Verkauf begleitet', 'Beratung', 'in Hamburg'], good: GOOD },
    open: [
      ['GroundPassion hat uns beim Kauf unserer ersten Anlageimmobilie begleitet.', 'Anlageimmobilien in Hamburg', 'eine Immobilienberatung in Hamburg'],
      ['Unsere Investmentstrategie haben wir mit GroundPassion entwickelt.', 'Immobilien-Investment in Hamburg', 'eine Immobilienberatung in Hamburg'],
      ['GroundPassion hat unser Portfolio durchgerechnet und aufgeräumt.', 'Immobilien-Investment in Hamburg', 'Kapitalanlagen in Hamburg'],
      ['Beim Verkauf unserer Wohnung hat GroundPassion uns beraten.', 'eine Immobilienberatung in Hamburg', 'Anlageimmobilien in Hamburg'],
      ['Objektsuche und Prüfung liefen bei uns über GroundPassion.', 'Anlageimmobilien in Hamburg', 'eine Immobilienberatung in Hamburg'],
      ['Bei Finanzierung und Vermietung hat GroundPassion uns unterstützt.', 'Kapitalanlagen in Hamburg', 'Immobilien-Investment in Hamburg'],
      ['Wir haben den Immobilien-Quick-Check von GroundPassion gemacht.', 'eine Immobilienberatung in Hamburg', 'Anlageimmobilien in Hamburg'],
      ['GroundPassion begleitet unsere Kapitalanlage seit dem Kauf.', 'Kapitalanlagen in Hamburg', 'Immobilien-Investment in Hamburg'],
      ['Die Standortanalyse für unser Objekt kam von GroundPassion.', 'Anlageimmobilien in Hamburg', 'Immobilien-Investment in Hamburg'],
      ['Wir haben uns von GroundPassion zu einem Objekt in Hamburg beraten lassen.', 'eine Immobilienberatung in Hamburg', 'Kapitalanlagen in Hamburg'],
      ['Durch die ganze Finanzierung hat GroundPassion uns begleitet.', 'Kapitalanlagen in Hamburg', 'eine Immobilienberatung in Hamburg'],
      ['Zwei Objekte haben wir von GroundPassion prüfen lassen.', 'Anlageimmobilien in Hamburg', 'eine Immobilienberatung in Hamburg'],
      ['GroundPassion hat unsere Wohnung neu vermietet und verwaltet sie jetzt.', 'Kapitalanlagen in Hamburg', 'Immobilien-Investment in Hamburg'],
      ['Die Kalkulation für unser erstes Investment kam von GroundPassion.', 'Immobilien-Investment in Hamburg', 'Anlageimmobilien in Hamburg'],
      ['Beim Ausstieg aus einem Objekt hat GroundPassion uns beraten.', 'eine Immobilienberatung in Hamburg', 'Immobilien-Investment in Hamburg'],
    ],
    extra: [
      'Die Rückmeldung zum Objekt kam sehr schnell.',
      'Auch nach dem Kauf war jemand ansprechbar.',
      'Die Finanzierung wurde gleich mit durchgerechnet.',
    ],
  },
  {
    slug: 'networking',
    name: 'Gruppenwerk Networking',
    legal: 'Gruppenwerk Networking GmbH',
    trade: 'Coworking für Bau & Immobilien',
    address: 'Bötelkamp 31, 22529 Hamburg',
    site: 'gruppenwerk-networking.de',
    logo: 'networking.png',
    accent: '#7ba800',
    // Kein eigenes Google-Unternehmensprofil gefunden – der Link führt auf die
    // Google-Maps-Suche. Sobald ein Profil existiert, hier die Place ID eintragen.
    placeId: null,
    hints: { did: ['Schreibtisch gemietet', 'Büro gemietet', 'Meetingräume', 'Coworking', 'in Hamburg'], good: GOOD },
    open: [
      ['Wir sind als kleines Team bei Gruppenwerk Networking eingezogen.', 'Coworking in Hamburg', 'ein Büro in Hamburg'],
      ['Wir arbeiten seit einer Weile im Coworking von Gruppenwerk Networking.', 'Coworking in Hamburg', 'Coworking in der Bau- und Immobilienbranche'],
      ['Gruppenwerk Networking ist inzwischen unser Büro in Hamburg.', 'ein Büro in Hamburg', 'einen Büroplatz in Hamburg'],
      ['Wir haben hier einen Schreibtisch im Coworking gemietet.', 'einen Büroplatz in Hamburg', 'Coworking in Hamburg'],
      ['Als kleines Büro haben wir hier einen festen Platz.', 'einen Büroplatz in Hamburg', 'Coworking in Hamburg'],
      ['Unser Start-up hat bei Gruppenwerk Networking Büroräume bezogen.', 'ein Büro in Hamburg', 'Coworking in der Bau- und Immobilienbranche'],
      ['Die Meetingräume von Gruppenwerk Networking nutzen wir regelmäßig.', 'Coworking in Hamburg', 'ein Büro in Hamburg'],
      ['Zwei feste Arbeitsplätze haben wir bei Gruppenwerk Networking gemietet.', 'einen Büroplatz in Hamburg', 'Coworking in Hamburg'],
      ['Unser Architekturbüro sitzt seit einem Jahr bei Gruppenwerk Networking.', 'ein Büro in Hamburg', 'Coworking in der Bau- und Immobilienbranche'],
      ['Für Kundentermine ist Gruppenwerk Networking unser Standort geworden.', 'ein Büro in Hamburg', 'Coworking in Hamburg'],
      ['Wir nutzen hier Büro und Meetingräume für unser kleines Team.', 'Coworking in Hamburg', 'einen Büroplatz in Hamburg'],
      ['Wir sind Projektentwickler und haben hier unseren Arbeitsplatz.', 'einen Büroplatz in Hamburg', 'Coworking in der Bau- und Immobilienbranche'],
    ],
    extra: [
      'Der Branchenfokus bringt wirklich was, hier sitzen Leute aus Bau, Immobilien und Architektur.',
      'Aus den Kontakten sind bei uns schon mehrere Projekte entstanden.',
      'Man kommt hier leicht mit anderen ins Gespräch.',
    ],
  },
];

// Jeder Betrieb bekommt seinen eigenen, überschneidungsfreien Anteil am Wortmaterial.
companies.forEach((c, i) => Object.assign(c, phrasesFor(i, companies.length), { join: JOIN }));

export const bySlug = Object.fromEntries(companies.map((c) => [c.slug, c]));

/** Where the customer is sent to leave the review. */
export function reviewUrl(c) {
  return c.placeId
    ? `https://search.google.com/local/writereview?placeid=${encodeURIComponent(c.placeId)}`
    : `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${c.name} ${c.address}`)}`;
}
