// Wortmaterial für den Textgenerator.
//
// Wichtig: die Pools werden per `phrasesFor()` fest auf die Betriebe aufgeteilt.
// Jeder Betrieb bekommt seinen eigenen, überschneidungsfreien Satz an Bausteinen.
// Dadurch kann derselbe Satz nie bei zwei Betrieben auftauchen — genau das Muster,
// das eine Gruppe verbundener Profile sonst als abgestimmt erkennbar macht.
//
// Die QUALITY-Einträge sind Hauptsätze in Kleinschreibung, damit sie sich
// grammatisch sauber einzeln oder paarweise ("… und …", "…, …") verbinden lassen.

export const QUALITY = [
  'die Termine wurden eingehalten',
  'die Absprachen haben von Anfang bis Ende gestimmt',
  'das Angebot war transparent und ohne versteckte Posten',
  'die Baustelle war jeden Abend besenrein',
  'wir wurden die ganze Zeit auf dem Laufenden gehalten',
  'die Arbeit wurde sauber ausgeführt',
  'das Team war freundlich und zuverlässig',
  'es gab keine Diskussionen über Kleinigkeiten',
  'der Termin kam schneller zustande als erwartet',
  'die Kosten sind im Rahmen geblieben',
  'man hat uns ehrlich beraten',
  'alles lief von der Anfrage bis zur Abnahme reibungslos',
  'die Handwerker waren pünktlich',
  'Rückfragen wurden sofort beantwortet',
  'am Ende wurde alles ordentlich hinterlassen',
  'die Qualität stimmt bis ins Detail',
  'wir mussten uns um nichts kümmern',
  'der Ablauf war gut organisiert',
  'die Beratung vorab hat wirklich geholfen',
  'es wurde mitgedacht statt nur abgearbeitet',
  'die Ausführung war sorgfältig',
  'die Kommunikation war jederzeit klar',
  'auch kurzfristige Änderungen waren kein Problem',
  'das Ergebnis übertrifft unsere Erwartungen',
  'der Preis war fair',
  'wir wurden ernst genommen',
  'die Zusammenarbeit war unkompliziert',
  'die Zusagen wurden alle eingehalten',
  'es wurde ordentlich abgedeckt und geschützt',
  'der Zeitplan hat gepasst',
  'die Arbeit wurde ohne Verzögerung fertig',
  'man merkt die Erfahrung',
  'die Ansprechpartner waren immer erreichbar',
  'kleinere Mängel wurden sofort behoben',
  'wir haben uns gut aufgehoben gefühlt',
  'das Ergebnis sieht sehr gut aus',
  'die Abrechnung war nachvollziehbar',
  'die Truppe war höflich und rücksichtsvoll',
  'alles wurde vorher in Ruhe erklärt',
  'der Aufwand wurde realistisch eingeschätzt',
  'die Arbeiten liefen ohne Störung für uns',
  'die Absprachen wurden schriftlich festgehalten',
  'es wurde nichts schöngeredet',
  'die Umsetzung entsprach genau der Absprache',
  'wir hatten einen festen Ansprechpartner',
  'die Anfahrt kam schnell',
  'die Arbeit wurde gründlich gemacht',
  'das Preis-Leistungs-Verhältnis stimmt',
  'es wurde sauber gearbeitet',
  'der Kontakt war durchweg angenehm',
  'wir sind mit dem Ergebnis sehr zufrieden',
  'die Termine wurden von sich aus bestätigt',
  'auf die Zusagen war Verlass',
  'die Arbeiten wurden zügig erledigt',
  'es wurde auf unsere Wünsche eingegangen',
  'die Vorbereitung war gut durchdacht',
  'das Material war sichtbar hochwertig',
  'die Abnahme lief unkompliziert',
  'die Mitarbeiter waren gut eingespielt',
  'wir wurden nie im Unklaren gelassen',
  'der Aufwand hat sich gelohnt',
  'die Lösung war praktisch und durchdacht',
  'es wurde ohne Hektik gearbeitet',
  'die Baustelle war jederzeit sicher',
  'das Angebot kam innerhalb weniger Tage',
  'wir haben ehrliche Auskünfte bekommen',
  'die Arbeiten wurden termingerecht abgeschlossen',
  'die Handwerker waren gut ausgerüstet',
  'das Ergebnis ist sauber verarbeitet',
  'die Betreuung war persönlich',
  'es hat alles auf Anhieb funktioniert',
  'wir würden nichts anders machen wollen',
  'der Kostenvoranschlag hat am Ende gestimmt',
  'es wurde ohne großes Aufhebens erledigt',
  'die Arbeiten wurden gut untereinander abgestimmt',
  'wir haben schnell einen Rückruf bekommen',
  'das Team hat sauber und leise gearbeitet',
  'die Ausführung war handwerklich einwandfrei',
  'wir konnten uns voll darauf verlassen',
  'es wurde auf Details geachtet',
  'die Baustelle war gut abgesichert',
  'der Aufwand wurde vorher klar benannt',
  'die Terminplanung war verlässlich',
  'es wurde hinterher ordentlich aufgeräumt',
  'die Leute waren gut gelaunt und motiviert',
  'der Betrieb hat sich Zeit genommen',
  'wir haben verständliche Erklärungen bekommen',
  'die Umsetzung ging schneller als gedacht',
  'das Ergebnis ist wirklich gelungen',
  'es lief alles nach Plan',
];

export const RECOMMEND = [
  'für {kw} eine klare Empfehlung',
  'wir können den Betrieb für {kw} nur weiterempfehlen',
  'wer {kw} sucht, ist hier richtig',
  'absolut empfehlenswert für {kw}',
  'von uns eine klare Empfehlung für {kw}',
  'top Adresse für {kw}',
  'wir würden für {kw} jederzeit wieder anrufen',
  'für {kw} können wir das nur empfehlen',
  'bei {kw} ist man hier gut aufgehoben',
  'eine echte Empfehlung für {kw}',
  'wir empfehlen den Betrieb für {kw} gerne weiter',
  'für {kw} die richtige Adresse in der Region',
  'wer {kw} braucht, sollte hier anfragen',
  'für {kw} uneingeschränkt zu empfehlen',
  'bei {kw} würden wir wieder hierher gehen',
  'klare Weiterempfehlung für {kw}',
  'für {kw} ohne Einschränkung zu empfehlen',
  'wir sind für {kw} sehr froh über diese Wahl',
  'für {kw} lohnt sich die Anfrage',
  'wer {kw} vergeben will, ist hier gut beraten',
  'für {kw} eine sichere Wahl',
  'wir empfehlen das für {kw} ohne zu zögern',
  'bei {kw} ganz klar eine Empfehlung',
  'für {kw} kann man das guten Gewissens empfehlen',
  'für {kw} jederzeit gerne wieder',
  'wer {kw} plant, sollte hier anfragen',
  'für {kw} sehr zu empfehlen',
  'unsere Empfehlung für {kw}',
  'für {kw} hat sich das voll gelohnt',
  'bei {kw} eine klare Sache',
  'für {kw} definitiv weiterzuempfehlen',
  'wer {kw} sucht, bekommt hier gute Arbeit',
  'für {kw} eine ehrliche Empfehlung',
  'wir würden für {kw} sofort wieder beauftragen',
  'für {kw} bestens geeignet',
  'bei {kw} muss man hier nicht lange suchen',
  'für {kw} rundum zu empfehlen',
  'wer {kw} braucht, ist hier gut aufgehoben',
  'für {kw} können wir den Betrieb weiterempfehlen',
  'für {kw} eine gute Wahl',
  'wir empfehlen den Betrieb bei {kw} weiter',
  'für {kw} ohne Wenn und Aber zu empfehlen',
  'wer {kw} vor sich hat, sollte hier anrufen',
  'für {kw} wirklich empfehlenswert',
  'bei {kw} kann man hier nichts falsch machen',
  'bei {kw} eine klare Weiterempfehlung von uns',
  'für {kw} genau die richtige Wahl',
  'wer {kw} anfragt, macht nichts falsch',
  'für {kw} können wir das ruhigen Gewissens empfehlen',
  'bei {kw} lohnt sich der Anruf',
  'für {kw} eine ganz klare Empfehlung von uns',
  'wer {kw} sucht, sollte hier nachfragen',
  'für {kw} in jedem Fall zu empfehlen',
  'bei {kw} würden wir wieder so entscheiden',
  'für {kw} eine verlässliche Adresse',
  'wir empfehlen den Betrieb für {kw} uneingeschränkt',
  'für {kw} absolut die richtige Entscheidung',
  'wer {kw} vergibt, ist hier richtig',
  'für {kw} kann man hier bedenkenlos anfragen',
  'bei {kw} sind wir sehr zufrieden gewesen',
  'für {kw} klar weiterzuempfehlen',
  'wer {kw} braucht, findet hier gute Arbeit',
  'für {kw} eine Empfehlung ohne Einschränkung',
];

export const CLOSER = [
  'Vielen Dank dafür!', 'Weiter so!', 'Danke an das ganze Team.',
  'So macht das Spaß.', 'Gerne wieder.', 'Wir kommen wieder.',
  'Danke für die gute Arbeit.', 'Genau so soll es sein.', 'Rundum zufrieden.',
  'Nichts zu beanstanden.', 'Sehr gerne wieder.', 'Das hat gepasst.',
  'Danke für die Zuverlässigkeit.', 'Top gemacht.', 'Alles bestens.',
  'Weiterempfehlung inklusive.', 'Danke für die schnelle Umsetzung.',
  'So wünscht man sich das.', 'Wir sind sehr zufrieden.',
  'Danke für die saubere Arbeit.', 'Hat alles bestens geklappt.',
  'Kann man so lassen.', 'Danke für die ehrliche Beratung.',
  'Bestens gelaufen.', 'Wir sind froh, dass wir angefragt haben.',
  'Danke für alles.', 'Absolut in Ordnung.',
  'Sehr empfehlenswert.', 'Danke nochmal!', 'Alles gut.', 'Klare Sache.',
  'Wir sind rundum zufrieden.', 'Danke für die Mühe.', 'Hat gut geklappt.',
  'Prima gelaufen.', 'Danke für den Einsatz.', 'Alles top.',
  'Wir melden uns wieder.', 'Sehr gute Erfahrung.', 'Danke dafür.',
  'Sauber gemacht.', 'Empfehlung von uns.', 'Danke für die Geduld.',
  'Beim nächsten Mal wieder.', 'Wirklich gut gemacht.', 'Vielen Dank!',
  'Da passt alles.', 'Danke für die Beratung.', 'Sehr ordentlich.',
  'Hat uns überzeugt.', 'Wir bleiben dabei.', 'Danke für die Umsetzung.',
  'Gute Arbeit.',
];

export const JOIN = [' und ', ', ', ' — '];

/** Teilt die Pools überschneidungsfrei auf `total` Betriebe auf. */
export function phrasesFor(index, total) {
  const slice = (pool) => pool.filter((_, i) => i % total === index);
  return { quality: slice(QUALITY), recommend: slice(RECOMMEND), closer: slice(CLOSER) };
}
