// Wortmaterial für den Textgenerator.
//
// Zielregister: so, wie Leute tatsächlich eine Google-Bewertung tippen. Kurz,
// oft ohne Artikel ("Termin hat gepasst, Preis war fair"), manchmal nur ein
// Fragment. Bewusst KEIN Amtsdeutsch ("die Ausführung war handwerklich
// einwandfrei") und keine Gedankenstriche — beides liest sich sofort geschrieben
// statt gesprochen.
//
// Die Pools werden per `phrasesFor()` fest auf die Betriebe aufgeteilt. Jeder
// Betrieb bekommt seinen eigenen, überschneidungsfreien Satz an Bausteinen,
// damit derselbe Satz nie bei zwei Profilen der Gruppe auftaucht.
//
// QUALITY-Einträge sind kleingeschrieben, damit sie sich einzeln oder paarweise
// verbinden lassen. Sie müssen nach ", " und nach " und " funktionieren und
// alleinstehend als Satz taugen.

export const QUALITY = [
  'Termin hat gepasst',
  'Preis war fair',
  'alles sauber hinterlassen',
  'war alles wie besprochen',
  'Angebot kam schnell',
  'keine bösen Überraschungen',
  'wurde sauber gearbeitet',
  'waren pünktlich da',
  'Absprachen haben gepasst',
  'nichts zu meckern',
  'sieht richtig gut aus',
  'lief alles glatt',
  'wurde uns gut erklärt',
  'Rückmeldung kam sofort',
  'hat auf Anhieb geklappt',
  'sehr freundliche Truppe',
  'da wurde mitgedacht',
  'war zum vereinbarten Termin fertig',
  'Qualität stimmt',
  'Preis-Leistung passt',
  'sehr nette Leute',
  'ging schneller als gedacht',
  'am Ende wurde aufgeräumt',
  'alles gut organisiert',
  'es gab keine Diskussionen',
  'Kosten sind im Rahmen geblieben',
  'wurden ehrlich beraten',
  'man konnte sich drauf verlassen',
  'hat vom ersten Anruf an gepasst',
  'war alles gut abgesprochen',
  'sehr sorgfältig gemacht',
  'die Handwerker waren pünktlich',
  'Fragen wurden sofort beantwortet',
  'wurde ordentlich abgeklebt',
  'keine versteckten Kosten',
  'war völlig unkompliziert',
  'hat alles wunderbar geklappt',
  'wir haben schnell einen Termin bekommen',
  'sieht super aus',
  'richtig saubere Arbeit',
  'da hat sich jemand Zeit genommen',
  'war pünktlich fertig',
  'Angebot war verständlich',
  'hat einfach alles gestimmt',
  'sehr angenehmer Kontakt',
  'wir wurden gut informiert',
  'Rechnung war nachvollziehbar',
  'es gab nie Stress',
  'auf unsere Wünsche wurde eingegangen',
  'Kleinigkeiten wurden direkt erledigt',
  'wurde leise gearbeitet',
  'die Anfahrt ging schnell',
  'wir hatten einen festen Ansprechpartner',
  'lief alles nach Plan',
  'da wurde nichts schöngeredet',
  'man merkt die Erfahrung',
  'ist wirklich gut geworden',
  'war gut vorbereitet',
  'sehr entspannte Abwicklung',
  'wurde gründlich gearbeitet',
  'hat alles gepasst',
  'Termine wurden von sich aus bestätigt',
  'war immer jemand erreichbar',
  'Material war sichtbar gut',
  'es wurde ohne Hektik gearbeitet',
  'Abnahme lief unkompliziert',
  'wir sind sehr zufrieden',
  'Zusagen wurden gehalten',
  'alles ordentlich abgedeckt',
  'kam sogar früher als geplant',
  'sehr höfliche Handwerker',
  'da wurde auf Details geachtet',
  'hat sich echt gelohnt',
  'war handwerklich top',
  'man wusste immer, woran man ist',
  'nichts liegen gelassen',
  'war fair kalkuliert',
  'wir wurden super beraten',
  'wurde genau so gemacht wie besprochen',
  'der Ablauf war durchdacht',
  'wir mussten nie hinterhertelefonieren',
  'wurde zügig gearbeitet',
  'kann sich sehen lassen',
  'alles bestens vorbereitet',
  'es wurde schnell reagiert',
  'sehr professionelle Truppe',
  'sauber verarbeitet',
  'Wort wurde gehalten',
  'lief entspannt ab',
  'wir sind rundum zufrieden',
];

// Die Suchbegriffe in `open` stehen im Akkusativ ("einen Maler in Hamburg").
// Deshalb darf {kw} hier nur hinter "für" oder als Objekt stehen — eine
// Dativ-Präposition ("bei {kw}") ergibt "Bei ein Büro in Hamburg ...".
export const RECOMMEND = [
  'für {kw} klare Empfehlung',
  'können wir für {kw} nur empfehlen',
  'wer {kw} sucht, ist hier richtig',
  'für {kw} auf jeden Fall zu empfehlen',
  'wir würden für {kw} sofort wieder anrufen',
  'für {kw} kann man hier nichts falsch machen',
  'für {kw} echt zu empfehlen',
  'wer {kw} braucht, sollte hier anfragen',
  'für {kw} jederzeit gerne wieder',
  'wir empfehlen den Betrieb für {kw} weiter',
  'für {kw} top Adresse',
  'für {kw} sind wir hier goldrichtig gelandet',
  'für {kw} können wir das nur weitersagen',
  'wer {kw} vorhat, ist hier gut aufgehoben',
  'für {kw} würden wir wieder hier anfragen',
  'wir gehen für {kw} nirgendwo anders mehr hin',
  'für {kw} absolut empfehlenswert',
  'wer {kw} sucht, kann hier ruhig anrufen',
  'für {kw} eine sichere Bank',
  'wir würden für {kw} wieder genauso entscheiden',
  'für {kw} klare Weiterempfehlung',
  'wir sagen das für {kw} gerne weiter',
  'für {kw} lohnt sich die Anfrage',
  'wer {kw} plant, sollte hier mal fragen',
  'für {kw} volle Empfehlung',
  'für {kw} kann man sich hier drauf verlassen',
  'für {kw} würden wir sofort wieder hierher',
  'wer {kw} braucht, findet hier gute Leute',
  'für {kw} können wir den Betrieb empfehlen',
  'für {kw} hat sich das bei uns gelohnt',
  'für {kw} definitiv zu empfehlen',
  'wer {kw} vergibt, macht hier nichts falsch',
  'für {kw} können wir das guten Gewissens empfehlen',
  'wir haben für {kw} genau richtig gewählt',
  'für {kw} ohne Wenn und Aber zu empfehlen',
  'wer {kw} sucht, ist hier gut beraten',
  'für {kw} rundum zu empfehlen',
  'für {kw} melden wir uns wieder hier',
  'für {kw} gerne weiterzuempfehlen',
  'wir sind froh, für {kw} hier angefragt zu haben',
  'für {kw} die richtige Adresse',
  'wer {kw} braucht, kann hier bedenkenlos anfragen',
  'für {kw} sehr zu empfehlen',
  'für {kw} muss man nicht lange weitersuchen',
  'für {kw} von uns eine klare Sache',
  'den Betrieb können wir für {kw} uneingeschränkt empfehlen',
  'für {kw} eine gute Wahl',
  'wer {kw} vor sich hat, sollte hier anrufen',
  'für {kw} wirklich empfehlenswert',
  'für {kw} lohnt sich der Anruf',
  'für {kw} können wir das ruhigen Gewissens empfehlen',
  'wer {kw} sucht, sollte hier mal nachfragen',
  'für {kw} in jedem Fall zu empfehlen',
  'wer {kw} sucht, wird hier sehr zufrieden sein',
  'für {kw} eine verlässliche Adresse',
  'wir würden für {kw} sofort wieder beauftragen',
  'für {kw} genau die richtige Wahl',
  'wer {kw} anfragt, macht nichts falsch',
  'für {kw} kann man hier bedenkenlos anfragen',
  'für {kw} würden wir wieder hierher gehen',
  'für {kw} klar weiterzuempfehlen',
  'wer {kw} braucht, findet hier gute Arbeit',
  'für {kw} uneingeschränkt zu empfehlen',
];

export const CLOSER = [
  'Danke nochmal!', 'Weiter so!', 'Danke an das Team.',
  'So macht das Spaß.', 'Gerne wieder!', 'Wir kommen wieder.',
  'Danke für die gute Arbeit.', 'Genau so soll es sein.', 'Rundum zufrieden.',
  'Nichts zu beanstanden.', 'Sehr gerne wieder.', 'Das hat gepasst.',
  'Danke, dass das so verlässlich lief.', 'Top gemacht.', 'Alles bestens.',
  'Empfehlung inklusive.', 'Danke für das Tempo.',
  'So wünscht man sich das.', 'Können wir nur empfehlen.',
  'Danke für die saubere Arbeit.', 'Hat alles geklappt.',
  'Kann man so lassen.', 'Danke für die ehrliche Beratung.',
  'Lief bestens.', 'Gut, dass wir gefragt haben.',
  'Danke für alles.', 'Völlig in Ordnung.',
  'Sehr empfehlenswert.', 'Danke dafür!', 'Alles gut.', 'Klare Sache.',
  'Top 👍', 'Danke für die Mühe.', 'Hat gut geklappt.',
  'Prima gelaufen.', 'Danke für den Einsatz.', 'Alles top.',
  'Wir melden uns wieder.', 'Sehr gute Erfahrung.', 'Danke!',
  'Sauber gemacht.', 'Von uns eine Empfehlung.', 'Danke für die Geduld.',
  'Beim nächsten Mal wieder.', 'Richtig gut gemacht.', 'Daumen hoch 👍',
  'Da passt alles.', 'Danke für die Beratung.', 'Sehr ordentlich.',
  'Hat uns überzeugt.', 'Wir bleiben dabei.', 'Nix zu meckern.',
  'Gute Arbeit 👍', 'Passt alles.',
];

// Wie zwei Qualitätsbausteine verbunden werden. '. ' erzeugt zwei kurze Sätze,
// was in echten Bewertungen häufiger vorkommt als jede Konjunktion. Kein
// Gedankenstrich: der ist das deutlichste Erkennungszeichen für generierten Text.
export const JOIN = [', ', ' und ', '. '];

/** Teilt die Pools überschneidungsfrei auf `total` Betriebe auf. */
export function phrasesFor(index, total) {
  const slice = (pool) => pool.filter((_, i) => i % total === index);
  return { quality: slice(QUALITY), recommend: slice(RECOMMEND), closer: slice(CLOSER) };
}
